kind: Secret
apiVersion: v1
metadata:
  name: authorino-app1-1431
  namespace: connlink
  labels:
    application_id: 7d7597ba
    authorino.kuadrant.io/managed-by: authorino
    key-type: app-key
data:
  api_key: cGVwZWdyaWxsbw==
type: Opaque
