{
 "title": "Gateway / Custom Pod Metrics",
 "tags": [
  "openshift",
  "gateway",
  "envoy"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "connlink" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~'$namespace'}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Active Connections (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{namespace=~'$namespace', pod=~'$pod'}) by (pod)",
     "legendFormat": "{{pod}} active cx"
    }
   ]
  },
  {
   "title": "HTTP connections (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{namespace=~'$namespace', pod=~'$pod'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP status codes (global)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[1m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'4..'}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'3..'}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'2..'}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "HTTP status codes (${pod})",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[1m])) by (pod)",
     "legendFormat": "{{pod}}: 5XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'4..'}[1m])) by (pod)",
     "legendFormat": "{{pod}}: 4XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'3..'}[1m])) by (pod)",
     "legendFormat": "{{pod}}: 3XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'2..'}[1m])) by (pod)",
     "legendFormat": "{{pod}}: 2XX"
    }
   ]
  },
  {
   "title": "Upstream status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[1m]))",
     "legendFormat": "5XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'4..'}[1m]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'3..'}[1m]))",
     "legendFormat": "3XX"
    },
    {
     "expr": "sum(rate(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'2..'}[1m]))",
     "legendFormat": "2XX"
    }
   ]
  },
  {
   "title": "errors / min (${pod})",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[1m])) by (pod)",
     "legendFormat": "{{pod}}: 5xx errors"
    }
   ]
  },
  {
   "title": "Total Gateway 5XX errors (last hour)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[1h]))"
    }
   ]
  },
  {
   "title": "Total Gateway 5XX errors (last 6h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[6h]))"
    }
   ]
  },
  {
   "title": "Total Gateway 5XX errors (last 12h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[12h]))"
    }
   ]
  },
  {
   "title": "Total Gateway 5XX errors (last 24h)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(istio_requests_total{namespace=~'$namespace', pod=~'$pod', reporter=\"source\", response_code=~'5..'}[24h]))"
    }
   ]
  },
  {
   "title": "Gateway Upstream Request Rate (by cluster)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_count{cluster_name!~\"agent|prometheus_stats|xds-grpc\"}[1m])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~'$namespace', pod=~'$pod', phase='Running'})"
    }
   ]
  },
  {
   "title": "Unavailable pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~'$namespace', pod=~'$pod', phase!='Running'})"
    }
   ]
  },
  {
   "title": "Pods distributed on hosts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod'}) by (node))"
    }
   ]
  },
  {
   "title": "Max pods restarts (last 5 minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(sum(delta(kube_pod_container_status_restarts_total{namespace=~'$namespace', pod=~'$pod'}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Pod count (total, avail, unvail) and pods hosts distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=~'$namespace', pod=~'$pod'})",
     "legendFormat": "total-pods"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~'$namespace', pod=~'$pod', phase='Running'})",
     "legendFormat": "avail-pods"
    },
    {
     "expr": "count(kube_pod_info{namespace=~'$namespace', pod=~'$pod'}) - sum(kube_pod_status_phase{namespace=~'$namespace', pod=~'$pod', phase='Running'})",
     "legendFormat": "unavail-pods"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod'}) by (node))",
     "legendFormat": "used-hosts"
    }
   ]
  },
  {
   "title": "Pods restarts (last 5 minutes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=~'$namespace', pod=~'$pod'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'$pod'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'$pod'}) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~'$namespace', pod=~'$pod'}) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod', container!=''}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Memory Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod', container!=''}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod', container!=''}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~'$namespace', pod=~'$pod', container!=''}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=~'$namespace', pod=~'$pod'}) by (pod)"
    }
   ]
  },
  { "title": "Network Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~'$namespace', pod=~'$pod'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~'$namespace', pod=~'$pod'}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}